vault_token: "{{ lookup('ansible.builtin.env', 'vault_token') }}"
secrets:  "{{lookup('hashi_vault', 'secret=ci-server/data/ci-secrets token={{vault_token}} url=https://vault-internal.rajdevops.online:8200 validate_certs=false')}}"